version: '3'
services:
  hugo:
    image: registry.gitlab.com/pages/hugo:latest
    env_file: .env
    entrypoint: ["hugo"]
    command: "server --buildDrafts --bind 0.0.0.0"
    volumes:
      - .:/srv/app:Z
    working_dir: /srv/app
    ports:
      - "1313:1313"
  aws:
    image: amaysim/aws:1.2.0
    env_file: .env
    volumes:
      - .:/srv/app:Z
    working_dir: /srv/app
  stacker:
    image: amaysim/stacker:latest
    env_file: .env
    entrypoint: stacker
    volumes:
      - .:/stacks:Z
      - ~/.aws:/root/.aws:Z

  envvars:
    image: flemay/envvars:0.0.4
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work

  cfn-python-lint:
    image: amaysim/cfn-python-lint:latest
    network_mode: "none"
    entrypoint: ''
      - .:/srv/app:Z

  write-good:
    image: aarongorka/write-good:latest
    network_mode: "none"
    working_dir: /srv/app
    volumes:
      - .:/srv/app:Z
